-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,                                                   
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT 
	  d.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.dim_products AS d
INNER JOIN gold.fact_sales AS f 
	  ON d.product_key=f.product_key
GROUP BY d.category
ORDER BY total_revenue DESC


-- What is the total revenue generated by each customer?
SELECT 
	  d.customer_key,
SUM(f.sales_amount) AS total_revenue
FROM gold.dim_customers AS d
LEFT JOIN gold.fact_sales AS f 
	  ON d.customer_key=f.customer_key
GROUP BY d.customer_key
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
